version: "3.7"

services:
  database_rampup:
    image: postgres
    container_name: database_rampup
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rampup
      - POSTGRES_DB=person_crud
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: person_crud
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local